Repository 42EASY/PongPongPingPong, pull requests merged in 2024-04, with the labels that each got.

#178 feat: 게임 관련 disconnect 구현
  backend/transcendence/games/game_consumer.py
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/games/game_room_consumer.py
  backend/transcendence/games/test_game_consumer.py
  backend/transcendence/games/test_game_queue_consumer.py
  backend/transcendence/games/test_game_room_consumer.py
Labels: feat✨

#179 feat: ChatConsumer 차단 유저 관련 기능 추가
  backend/transcendence/chat/consumers.py
Labels: feat✨

#182 feat: 게임 큐 cancel action 구현
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/games/test_game_queue_consumer.py
Labels: feat✨

#184 fix: 게임방에 유저 입장 시 플레이어 정보 반환
  backend/transcendence/games/game_room_consumer.py
  backend/transcendence/games/test_game_room_consumer.py
Labels: fix🛠️

#185 fix: chat & notify 수정 및 차단 & 오프라인 유저 관련 기능 구현
  backend/transcendence/chat/consumers.py
  backend/transcendence/notify/consumer.py
Labels: feat✨, fix🛠️

#187 fix: 2차인증 비동기 적용
  backend/transcendence/games/migrations/0001_initial.py
  backend/transcendence/members/migrations/0001_initial.py
  backend/transcendence/social/migrations/0001_initial.py
  backend/transcendence/tournaments/migrations/0001_initial.py
  frontend/src/components/Login/Redirect.js
  frontend/src/components/Modal/ModalsInfo.js
  frontend/src/components/Register/SubmitButton.js
  frontend/src/components/Register/TwoFactorAuth.js
  frontend/src/styles/nav.css
Labels: feat✨, fix🛠️

#183 fix: 모달 함수 수정
  frontend/src/components/Modal/Modal.js
  frontend/src/components/Modal/ModalsInfo.js
  frontend/src/styles/modal.css
Labels: fix🛠️

#192 fix: 게임 방 소켓 자잘한 오류 수정
  backend/transcendence/games/game_consumer.py
  backend/transcendence/games/test_game_consumer.py
Labels: fix🛠️

#194 fix: main url에 id 추가
  frontend/src/Router.js
  frontend/src/components/Friends/Options.js
  frontend/src/components/Nav/FastGameStart.js
  frontend/src/components/Nav/InviteQueue.js
  frontend/src/components/Nav/JoinQueue.js
  frontend/src/components/Nav/NavApi.js
  frontend/src/pages/Main.js
  frontend/src/pages/Nav.js
  frontend/src/state/State.js
Labels: fix🛠️

#197 fix: chat 프로필 API 연결
  frontend/src/components/Chat/Profile/ContactInfo.js
  frontend/src/components/Chat/Profile/Info.js
  frontend/src/components/Chat/Profile/InfoBtn.js
  frontend/src/components/Chat/Profile/Title.js
  frontend/src/pages/Profile.js
  frontend/src/styles/sidebar.css
Labels: feat✨, fix🛠️

#199 feat: 채팅방 나가기 기능 구현 & timestamp 추가
  backend/transcendence/chat/consumers.py
  frontend/src/components/Chat/Chat.js
  frontend/src/components/Chat/ChatList.js
  frontend/src/components/Chat/ChatRoom/ChatContent.js
  frontend/src/pages/Chat.js
  frontend/src/pages/ChatRoom.js
  frontend/src/state/ChatState.js
Labels: feat✨, fix🛠️

#201 fix: main의 차단 해제 undefined 해결
  frontend/src/components/Main/MoreMenu.js
  frontend/src/components/Main/OtherBtn.js
Labels: fix🛠️

#203 fix: refresh token 관련 버그 픽스
  backend/transcendence/security/auth_views.py
  frontend/src/state/State.js
Labels: bug🐛

#204 feat: 노말과 토너먼트에 대한 dummy data 추가
  backend/docker_entrypoint.sh
  backend/transcendence/games/fixtures/game-data.json
  backend/transcendence/games/fixtures/participant-data.json
  backend/transcendence/games/fixtures/tournament-data.json
  backend/transcendence/games/fixtures/tournament-game-data.json
Labels: feat✨

#205 feat: socketManager 추가
  frontend/src/Router.js
  frontend/src/components/Login/Redirect.js
  frontend/src/components/Nav/InviteQueue.js
  frontend/src/components/Nav/JoinQueue.js
  frontend/src/pages/GameRoom.js
  frontend/src/pages/Nav.js
  frontend/src/state/JoinSocketManager.js
  frontend/src/state/RoomSocketManager.js
  frontend/src/styles/nav.css
Labels: feat✨, fix🛠️

#207 feat: bot 메세지 받아오기 구현
  backend/transcendence/chat/consumers.py
  backend/transcendence/games/game_consumer.py
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/games/game_room_consumer.py
  backend/transcendence/notify/consumer.py
  backend/transcendence/social/block_urls.py
  backend/transcendence/utils.py
Labels: feat✨

#209 fix: 토스트 순서 변경 및 채팅 기능 향상
  frontend/index.html
  frontend/src/components/Chat/Chat.js
  frontend/src/components/Chat/ChatRoom/BotContent.js
  frontend/src/pages/BotRoom.js
  frontend/src/pages/Chat.js
  frontend/src/pages/ChatRoom.js
  frontend/src/state/WebSocketManager.js
  frontend/src/styles/toast.css
Labels: feat✨, fix🛠️

#210 FIX: 토너먼트 id 반환 부분 수정 및 redis host 변경 등 세부 사항 변경
  backend/transcendence/games/distributed_lock.py
  backend/transcendence/games/game_room_consumer.py
  backend/transcendence/games/test_game_room_consumer.py
  backend/transcendence/social/friends_views.py
Labels: fix🛠️

#214 feat: 게임 소켓 action 추가 구현 및 수정
  backend/transcendence/games/game_consumer.py
  backend/transcendence/games/test_game_consumer.py
Labels: feat✨

#216 Fe/feat game socket
  backend/transcendence/games/distributed_lock.py
  frontend/src/Router.js
  frontend/src/components/Game/Board.js
  frontend/src/components/Game/EndBtn.js
  frontend/src/components/Game/EndConfetti.js
  frontend/src/components/Game/GameResult.js
  frontend/src/components/Modal/Modal.js
  frontend/src/components/Modal/ModalsInfo.js
  frontend/src/components/Nav/FastGameStart.js
  frontend/src/pages/EndGame.js
  frontend/src/pages/Game.js
  frontend/src/state/GameSocketManager.js
  frontend/src/styles/endgame.css
  frontend/src/styles/modal.css
Labels: feat✨

#218 fix: socket 관련 코드 수정
  frontend/src/components/Chat/ChatRoom/BotContent.js
  frontend/src/components/Friends/Options.js
  frontend/src/components/GameRoom/PercentBar.js
  frontend/src/components/Modal/ModalsInfo.js
  frontend/src/components/Nav/JoinQueue.js
  frontend/src/pages/Friends.js
  frontend/src/pages/GameRoom.js
  frontend/src/pages/Nav.js
  frontend/src/state/JoinSocketManager.js
Labels: bug🐛, fix🛠️

#219 fix: 상대의 channel_name이 갱신이 안되는 현상 수정
  backend/transcendence/games/game_consumer.py
Labels: bug🐛

#220 fix: pingpong 게임 중에 값이 갱신되지 않는 현상 수정
  backend/transcendence/games/game_consumer.py
  backend/transcendence/games/test_game_consumer.py
Labels: bug🐛

#224 feat: 게임전적 API 연결 & 무한스크롤 적용
  frontend/src/components/Friends/ListApi.js
  frontend/src/components/Main/GameHistory.js
  frontend/src/components/Main/GameResult.js
  frontend/src/components/Main/GameResults.js
  frontend/src/components/Main/Profile.js
  frontend/src/components/Main/TournamentResult.js
  frontend/src/components/Main/UserApi.js
  frontend/src/components/Nav/NavApi.js
  frontend/src/components/Register/SubmitButton.js
  frontend/src/components/Register/TwoFactorAuth.js
  frontend/src/pages/Main.js
  frontend/src/state/State.js
  frontend/src/styles/main.css
  frontend/src/styles/nav.css
Labels: feat✨

#225 fix: 토너먼트 전적을 받아올 때 원하는 size 대로 반환하지 않는 현상 수정
  backend/transcendence/members/views.py
Labels: bug🐛

#226 fix: round_start broadcast가 안되는 현상 수정
  backend/transcendence/games/game_consumer.py
Labels: bug🐛

#227 feat: 토너먼트 방에서 disconnect 시에 처리 추가
  backend/transcendence/games/game_room_consumer.py
Labels: feat✨

#228 feat: bot 관련 기능
  backend/Dockerfile
  backend/transcendence/chat/consumers.py
  backend/transcendence/games/game_consumer.py
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/games/game_room_consumer.py
  backend/transcendence/utils.py
  frontend/index.html
  frontend/src/components/Chat/Bot.js
  frontend/src/components/Chat/ChatRoom/BotContent.js
  frontend/src/pages/BotRoom.js
  frontend/src/pages/Chat.js
  frontend/src/pages/ChatRoom.js
Labels: feat✨, fix🛠️

#235 fix: 게임의 start, end time이 잘 저장 안되는 현상 수정
  backend/transcendence/games/game_consumer.py
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/games/game_room_consumer.py
Labels: bug🐛

#237 fix: scroll , joingame과 gameroom 소켓 수정
  frontend/src/components/Chat/ChatRoom/BotContent.js
  frontend/src/components/Modal/Modal.js
  frontend/src/components/Modal/ModalsInfo.js
  frontend/src/pages/ChatRoom.js
  frontend/src/pages/GameRoom.js
  frontend/src/pages/Nav.js
  frontend/src/state/JoinSocketManager.js
  frontend/src/state/RoomSocketManager.js
Labels: fix🛠️

#239 fix: 게임 나가기 버튼 클릭 이후 게임 매칭이 되지 않는 현상 수정
  backend/transcendence/games/game_consumer.py
  frontend/src/components/Nav/JoinQueue.js
Labels: bug🐛

#240 fix: 빠른 게임 후 스크롤 동작하도록 수정
  frontend/src/components/Modal/Modal.js
  frontend/src/pages/Main.js
Labels: bug🐛

#236 refactor: wss, https으로 통신하도록 변경
  .gitignore
  backend/Dockerfile
  backend/docker_entrypoint.sh
  backend/transcendence/run_daphne.py
  backend/transcendence/security/auth_views.py
  backend/transcendence/transcendence/asgi.py
  backend/transcendence/transcendence/settings.py
  docker-compose.yml
  frontend/src/components/Login/LoginButton.js
  frontend/src/state/ChatSocketManager.js
  frontend/src/state/JoinSocketManager.js
  frontend/src/state/State.js
  frontend/src/state/WebSocketManager.js
  nginx/Dockerfile
  nginx/default
Labels: refactor🪡

#241 style: 읽지 않은 메세지 개수 css 수정
  frontend/src/components/Chat/Bot.js
  frontend/src/pages/Chat.js
  frontend/src/styles/sidebar.css
Labels: style💅

#244 fix: cors 설정
  backend/transcendence/transcendence/settings.py
Labels: bug🐛

#246 refactor: 서버에서 계산하도록 게임 로직 수정
  backend/transcendence/games/game_board_consumer.py
  backend/transcendence/transcendence/routing.py
  frontend/src/components/Game/RemoteBoard.js
  frontend/src/components/Modal/ModalsInfo.js
  frontend/src/pages/Game.js
  frontend/src/state/GameBoardSocketManager.js
  frontend/src/state/State.js
Labels: fix🛠️, refactor🪡

#249 fix: 매칭 진행 중 의도치 않은 매칭 종료 후 게임 전적 페이지 400 뜨는 현상 수정
  backend/transcendence/games/game_queue_consumer.py
Labels: bug🐛

#251 fix: game over시에 result도 전송하도록 추가
  backend/transcendence/games/game_board_consumer.py
Labels: fix🛠️

#253 fix: 게임 전적을 start time 기준으로 내림차순 정렬
  backend/transcendence/members/views.py
Labels: fix🛠️

#255 fix: tournament, noraml로 나누어 player_info 처리
  frontend/src/components/Game/RemoteBoard.js
  frontend/src/pages/Game.js
Labels: fix🛠️

#257 bug: win or lose 판단 조건문 변경
  frontend/src/components/Game/GameResult.js
  frontend/src/pages/EndGame.js
Labels: bug🐛

#259 bug: 진 사람의 경우 루프가 안 끝나는 버그 수정
  backend/transcendence/games/game_board_consumer.py
Labels: bug🐛

#260 refactor: 토너먼트 결과 알림 기능 game_board 컨슈머로 이동
  backend/transcendence/games/game_board_consumer.py
Labels: refactor🪡

#261 refactor: game option에 관한 처리
  backend/transcendence/games/game_board_consumer.py
Labels: refactor🪡

#263 fix: 서버와 nginx 인증서 분리
  backend/Dockerfile
  backend/docker_entrypoint.sh
  backend/transcendence/run_daphne.py
  docker-compose.yml
  nginx/Dockerfile
  nginx/default
Labels: fix🛠️

#266 refactor: 비동기적으로 db에 접근하도록 변경
  backend/transcendence/games/game_board_consumer.py
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/games/game_room_consumer.py
Labels: refactor🪡

#265 Fe/fix socket connection
  frontend/src/pages/Game.js
  frontend/src/pages/GameRoom.js
  frontend/src/pages/Main.js
  frontend/src/pages/Nav.js
  frontend/src/state/GameBoardSocketManager.js
  frontend/src/state/RoomSocketManager.js
  frontend/src/state/State.js
Labels: fix🛠️

#268 bug: 게임 비정상 종료 시 승패 오류 수정
  backend/transcendence/games/game_board_consumer.py
Labels: bug🐛

#269 fix: game result가 없는 game도 반환하는 현상 수정
  backend/transcendence/members/views.py
Labels: bug🐛

#271 fix: 자기 자신과 게임이 매칭 되는 현상 수정
  backend/transcendence/games/game_queue_consumer.py
Labels: fix🛠️

#270 feat: socket interval
  frontend/src/components/Chat/ChatRoom/BotContent.js
  frontend/src/components/Main/UserApi.js
  frontend/src/pages/GameRoom.js
  frontend/src/pages/Nav.js
  frontend/src/state/ChatSocketManager.js
  frontend/src/state/JoinSocketManager.js
  frontend/src/state/State.js
  frontend/src/state/WebSocketManager.js
Labels: feat✨, fix🛠️

#273 fix: roomsocket disconnect
  frontend/src/pages/GameRoom.js
  frontend/src/state/RoomSocketManager.js
Labels: fix🛠️

#282 fix: register 페이지 버그 수정 및 로그인 없이 url로 페이지 이동 제한 적용
  frontend/src/App.js
  frontend/src/Router.js
  frontend/src/components/Register/Nickname.js
  frontend/src/components/Register/SubmitButton.js
  frontend/src/components/Register/TwoFactorAuth.js
  frontend/src/pages/BotRoom.js
  frontend/src/pages/Chat.js
  frontend/src/pages/ChatRoom.js
  frontend/src/pages/EndGame.js
  frontend/src/pages/Friends.js
  frontend/src/pages/Game.js
  frontend/src/pages/GameRoom.js
  frontend/src/pages/Login.js
  frontend/src/pages/Main.js
  frontend/src/pages/NotFound.js
  frontend/src/pages/Profile.js
  frontend/src/pages/Register.js
Labels: bug🐛, fix🛠️

#275 bug: socket이 싱글톤으로 관리되지 않는 현상
  frontend/src/components/Chat/Chat.js
  frontend/src/components/Login/Redirect.js
  frontend/src/pages/BotRoom.js
  frontend/src/pages/ChatRoom.js
  frontend/src/state/ChatSocketManager.js
  frontend/src/state/GameBoardSocketManager.js
  frontend/src/state/JoinSocketManager.js
  frontend/src/state/NotifySocketManager.js
  frontend/src/state/RoomSocketManager.js
  frontend/src/state/State.js
Labels: bug🐛

#281 fix: 빠진 예외처리 추가
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/members/views.py
  backend/transcendence/security/auth_views.py
  backend/transcendence/security/views.py
Labels: fix🛠️

#280 fix: channel_layer 설정 변경
  backend/transcendence/transcendence/settings.py
Labels: bug🐛

#278 fix: game board consumer 수정
  backend/transcendence/games/game_board_consumer.py
Labels: bug🐛, refactor🪡

#284 fix: 토너먼트 결승 게임을 위한 게임방에 입장이 안되는 현상 수정
  backend/transcendence/games/game_room_consumer.py
Labels: bug🐛

#286 style: gameroom 결승인 경우 css 수정
  frontend/src/pages/GameRoom.js
  frontend/src/styles/gameroom.css
Labels: style💅

#287 fix: 토너먼트 경기 종료 후 알림 오류 수정
  backend/transcendence/games/game_board_consumer.py
Labels: bug🐛

#288 fix: docker-compose 및 makefile 설정 변경
  Makefile
  backend/docker_entrypoint.sh
  docker-compose.yml
Labels: fix🛠️

#289 bug: api 재귀 인자 누락된 부분 수정
  frontend/src/components/Main/GameResults.js
  frontend/src/components/Register/TwoFactorAuth.js
Labels: bug🐛

#290 bug: display none>block 변경되지 않는 문제 임시 조치
  frontend/index.html
  frontend/src/pages/Register.js
Labels: bug🐛

#291 fix: 토너먼트 결승 중 disconnect 안되는 현상 수정
  backend/transcendence/games/game_room_consumer.py
Labels: bug🐛

#293 bug: 프론트 정리
  frontend/src/Router.js
  frontend/src/components/Chat/Profile/InfoBtn.js
  frontend/src/components/Friends/Blocked.js
  frontend/src/components/Friends/ListApi.js
  frontend/src/components/Game/Board.js
  frontend/src/components/Game/Info.js
  frontend/src/components/Game/RemoteBoard.js
  frontend/src/components/Login/Redirect.js
  frontend/src/components/Main/UserApi.js
  frontend/src/components/Modal/Modal.js
  frontend/src/components/Modal/addContent.js
  frontend/src/components/Nav/NavApi.js
  frontend/src/components/Register/TwoFactorAuth.js
  frontend/src/pages/BotRoom.js
  frontend/src/pages/Chat.js
  frontend/src/pages/ChatRoom.js
  frontend/src/pages/EndGame.js
  frontend/src/pages/Friends.js
  frontend/src/pages/Game.js
  frontend/src/pages/GameRoom.js
  frontend/src/pages/Login.js
  frontend/src/pages/Main.js
  frontend/src/pages/NotFound.js
  frontend/src/pages/Profile.js
  frontend/src/pages/Register.js
  frontend/src/state/State.js
  frontend/src/styles/modal.css
Labels: bug🐛
