Repository 42EASY/PongPongPingPong, pull requests merged in 2024-03, with the labels that each got.

#143 fix: 분산 락으로 동시성 문제 해결
  backend/transcendence/games/distributed_lock.py
  backend/transcendence/games/game_consumer.py
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/games/game_room_consumer.py
Labels: bug🐛

#144 fix: 경로 지정
  backend/transcendence/games/game_consumer.py
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/games/game_room_consumer.py
Labels: fix🛠️

#147 fix: websocket connect 시에 user 값 받아오도록 수정
  backend/transcendence/games/game_consumer.py
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/games/game_room_consumer.py
  backend/transcendence/games/test_game_consumer.py
  backend/transcendence/games/test_game_queue_consumer.py
  backend/transcendence/games/test_game_room_consumer.py
Labels: fix🛠️

#150 feat: mock 데이터 추가
  backend/database_init.sql
  docker-compose.yml
Labels: feat✨

#151 fix: 멤버 첫 로그인 로직 변경
  backend/transcendence/members/modelSerializer.py
  backend/transcendence/members/models.py
  backend/transcendence/members/views.py
  backend/transcendence/security/auth_views.py
  backend/transcendence/transcendence/settings.py
Labels: fix🛠️

#153 fix: 사용하지 않는 param들 정리
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/games/game_room_consumer.py
  backend/transcendence/games/test_game_consumer.py
  backend/transcendence/games/test_game_queue_consumer.py
  backend/transcendence/games/test_game_room_consumer.py
Labels: fix🛠️

#154 Fe/fix_modal
  frontend/src/components/Modal/Modal.js
  frontend/src/components/Modal/ModalsInfo.js
  frontend/src/components/Modal/addContent.js
  frontend/src/components/Modal/adddModal.js
  frontend/src/pages/Nav.js
  frontend/src/styles/modal.css
Labels: fix🛠️

#155 fix: game websocket 세세한 부분 수정
  backend/transcendence/games/game_consumer.py
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/games/game_room_consumer.py
  backend/transcendence/games/test_game_queue_consumer.py
Labels: fix🛠️

#157 fix: friends 친구 목록, nav 검색 부분 수정
  frontend/src/Router.js
  frontend/src/components/Chat/Chat.js
  frontend/src/components/Friends/Blocked.js
  frontend/src/components/Friends/Blockeds.js
  frontend/src/components/Friends/Friend.js
  frontend/src/components/Friends/Friends.js
  frontend/src/components/Main/MoreMenu.js
  frontend/src/components/Main/OtherBtn.js
  frontend/src/components/Main/Profile.js
  frontend/src/components/Register/SubmitButton.js
  frontend/src/components/Register/TwoFactorAuth.js
  frontend/src/images/qr.png
  frontend/src/pages/ChatRoom.js
  frontend/src/pages/Friends.js
  frontend/src/pages/Main.js
  frontend/src/pages/Nav.js
  frontend/src/pages/NotFound.js
  frontend/src/styles/nav.css
  frontend/src/styles/notfound.css
  frontend/src/styles/sidebar.css
Labels: fix🛠️

#159 fix: mock data
  backend/database_init.sql
  backend/docker_entrypoint.sh
  backend/transcendence/members/fixtures/members-data.json
  backend/transcendence/social/fixtures/Friend-data.json
  docker-compose.yml
Labels: fix🛠️

#162 feat: restart daphne
  backend/Dockerfile
  backend/docker_entrypoint.sh
  backend/transcendence/run_daphne.py
  docker-compose.yml
Labels: feat✨

#163 refactor: 채팅 기능과 알림 기능 분리
  backend/transcendence/chat/consumers.py
  backend/transcendence/notify/__init__.py
  backend/transcendence/notify/admin.py
  backend/transcendence/notify/apps.py
  backend/transcendence/notify/consumer.py
  backend/transcendence/notify/migrations/__init__.py
  backend/transcendence/notify/models.py
  backend/transcendence/notify/tests.py
  backend/transcendence/notify/views.py
  backend/transcendence/transcendence/routing.py
Labels: refactor🪡

#165 fix: state 추가, sidebar scroll 적용
  frontend/src/components/Chat/ChatRoom/ChatContents.js
  frontend/src/components/Chat/ChatRoom/Title.js
  frontend/src/pages/Chat.js
  frontend/src/pages/ChatRoom.js
  frontend/src/pages/Friends.js
  frontend/src/pages/Nav.js
  frontend/src/state/State.js
  frontend/src/styles/sidebar.css
Labels: fix🛠️

#167 feat: join_queue 소켓 추가
  frontend/src/components/Friends/Options.js
  frontend/src/components/GameRoom/WaitingPlayer.js
  frontend/src/components/Main/MoreMenu.js
  frontend/src/components/Nav/FastGameStart.js
  frontend/src/components/Nav/InviteQueue.js
  frontend/src/components/Nav/JoinQueue.js
  frontend/src/pages/Friends.js
  frontend/src/pages/GameRoom.js
Labels: feat✨

#170 fix: chatting input
  frontend/src/components/Chat/ChatRoom/ChatContents.js
  frontend/src/styles/sidebar.css
Labels: fix🛠️

#174 fix: 채팅방 오류 수정
  Makefile
  backend/transcendence/security/auth_views.py
  frontend/src/components/Chat/ChatList.js
  frontend/src/components/Login/Redirect.js
  frontend/src/pages/Chat.js
  frontend/src/pages/ChatRoom.js
  frontend/src/state/State.js
  frontend/src/styles/sidebar.css
Labels: fix🛠️

#175 fix: 게임 빠른 시작 시에 오류 발생 해결
  backend/transcendence/games/game_queue_consumer.py
  backend/transcendence/games/test_game_queue_consumer.py
Labels: bug🐛

#176 fix: bot content 추가
  frontend/src/components/Chat/Bot.js
  frontend/src/components/Chat/ChatRoom/BotContent.js
  frontend/src/components/Chat/ChatRoom/ChatContent.js
  frontend/src/components/Modal/GameResultTable.js
  frontend/src/components/Modal/TournamentTable.js
  frontend/src/components/Nav/JoinQueue.js
  frontend/src/pages/BotRoom.js
  frontend/src/pages/Chat.js
  frontend/src/pages/ChatRoom.js
  frontend/src/styles/modal.css
  frontend/src/styles/sidebar.css
Labels: feat✨
